# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ThePetApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'
  pod 'SDWebImageSwiftUI'

  target 'ThePetAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ThePetAppUITests' do
    # Pods for testing
  end

end
